language: node_js

sudo: required

node_js:
  - 'node'

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - source 

install:
  - yarn

script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "showonne"
  - git config user.email "showone896@gmail.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy

