# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Links: /links
  About: /about

# Author
author: Showonne


# Content
excerpt_link: More +

# highlight.js
highlight_theme: tomorrow-night
